GET http://localhost:8080/categories

###

POST http://localhost:8080/categories
Content-type: application/json

{
    "firstName":"Anand",
    "lastName":"Girardet",
    "birthDate":"01.03.1997",
    "email":"anandgirardet@gmail.com",
    "phone":"88079212",
    "password":"",
    "imageUrl":"",
}

###

GET http://localhost:8080/categories/3

###

DELETE http://localhost:8080/
Content-type: application/json

{
    "id":""
}

###

PUT http://localhost:8080/
Content-type: application/json

{
    "firstName":"Anand",
    "lastName":"Girardet",
    "birthDate":"01.03.1997",
    "email":"anandgirardet@gmail.com",
    "phone":"88079212",
    "password":"",
    "imageUrl":"",
}

###